### ISSUE TITLE
transparent cortex despite alpha=1.0 with MNE environment in Python 3

### ISSUE THREAD

**Issue by sbitzer** [nipy/PySurfer#258] opened 2018-10-15 20:53 UTC
Hi, I wondered whether you have come across this issue before:
![transparent_brain](https://user-images.githubusercontent.com/320128/46976869-e80df480-d0ca-11e8-868e-6b3d7a485ed6.png)

What you see is a medial view of an inflated right hemisphere with coloured labels on it. Some of the labels are on the lateral side and should not be seen in this view, but still are as indicated by the black annotation.

The call generating the brain was simply:
```
brain = Brain('fsaverage', hemi, 'inflated', cortex='low_contrast',
                      subjects_dir=sv.subjects_dir, background='w', 
                      foreground='k')
```
so the cortex should be opaque (alpha=1) per default. I added the labels using `brain.add_data`. The same code produces a correct opaque visualisation in an older Python 2 environment using wxpython.

This occurs in an MNE-Python environment installed per instructions on the MNE website, i.e., with [this yml-file](https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml).

System information:
Platform:      Linux-4.4.0-137-generic-x86_64-with-debian-jessie-sid
Python:        3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16)  [GCC 7.3.0]
Executable:    /home/bitzer/miniconda3/envs/mne_test/bin/python
CPU:           x86_64: 8 cores
Memory:        15.6 GB

mne:           0.16.2
numpy:         1.15.2 {blas=mkl_rt, lapack=mkl_rt}
scipy:         1.1.0
matplotlib:    2.2.2 {backend=Qt5Agg}

sklearn:       0.20.0
nibabel:       2.3.0
mayavi:        4.6.2 {qt_api=pyqt5}
pycuda:        Not found
skcuda:        Not found
pandas:        0.23.4

**Comment by mwaskom** [comment] 2018-10-15 21:01
You show how you're making the brain but not how you're putting the labels on it. Could you share that code? I suspect this is not really about transparency (seeing "through" the brain) but rather about the labels not going in the right place. Because of how the vertices are defined on fsaverage, if you show data on the wrong hemisphere (i.e. rois defined for the left hemisphere on the right mesh) something a lot like this can happen.

**Comment by sbitzer** [comment] 2018-10-15 22:43
The code for adding the data is as follows:
```
labels = mne.read_labels_from_annot('fsaverage', parc=parc, hemi='both')
labels = {l.name: l for l in labels}

for hemi in brain.geo.keys():
    # create data from source estimates
    V = brain.geo[hemi].x.size
    data = np.zeros((V, T))
    for name in [l for l in labels.keys() if l.endswith(hemi)]:
        data[labels[name].vertices, :] = values.xs(name, level='label')
    
    # plot
    brain.add_data(data, fmin, fmax, mid=fmid, center=center,
                   transparent=transparent, colormap=colormap, 
                   time=src_df.index.levels[1].values, 
                   time_label=time_label,
                   colorbar=colorbar, hemi=hemi, 
                   remove_existing=True)
```

The parcellation is HCPMMP1_5_8 which I created based on the instructions of the Human Connectome Project.

[HCPMMP1_5_8.zip](https://github.com/nipy/PySurfer/files/2480805/HCPMMP1_5_8.zip)

**Comment by mwaskom** [comment] 2018-10-16 14:15
A bit tough to say without a complete example but putting together the two snippets you've shown it looks like you're showing a unilateral surface and then putting bilateral labels on it, as I suspected. I'm not completely sure what `add_data` does with the `hemi` argument in the case of a unilateral surface, but it might just ignore it.

**Comment by sbitzer** [comment] 2018-10-17 06:55
Not quite: Everything inside the `for`-loop is hemisphere specific. The labels are unilateral, too. I select them for each hemisphere with `[l for l in labels.keys() if l.endswith(hemi)]`. Also, I make a data array based on the geometry of the hemisphere. As I understand it, the data array just gives color values for the vertices of the cortical surface represented in `brain`.

**Comment by mwaskom** [comment] 2018-10-17 11:29
But you’re not creating the Brain in the loop that you show, so that isn’t hemisphere specific. I’m sorry but I really can’t help if I’m forced to guess about what you’re actually doing.

**Comment by larsoner** [comment] 2018-10-17 14:39
> What you see is a medial view of an inflated right hemisphere with coloured labels on it. Some of the labels are on the lateral side and should not be seen in this view, but still are as indicated by the black annotation.

On some systems and graphics cards, the Z ordering / depth buffer gets messed up. Can you try using an `alpha=0.99` instead? Also try setting the cortex alpha itself to `0.99` instead of `1.0` to see if it helps?

**Comment by sbitzer** [comment] 2018-10-17 21:07
I tried using ``alpha=0.99`` for the call to ``Brain`` as well as ``add_data``, but it didn't change anything. Below is self-contained code reproducing the issue on my machine. I tested it also on a Windows machine with a fresh install of miniconda and the mne environment. There I don't see this issue. So it appears to be machine related.

```
import mne
from surfer import Brain

import numpy as np

T = 1

hemi = 'rh'
subjects_dir = 'mne_subjects'

labels = mne.read_labels_from_annot('fsaverage', parc='aparc', hemi=hemi)
labels = {l.name: l for l in labels}

N = 15
values = np.zeros(len(labels))
values[np.random.permutation(len(labels))[:N]] = np.random.rand(N)
values = {label: value for label, value in zip(labels.keys(), values)}

brain = Brain('fsaverage', hemi, 'inflated', cortex='low_contrast',
              subjects_dir=subjects_dir, background='w', 
              foreground='k')

V = brain.geo[hemi].x.size
data = np.zeros((V, T))
for name in [l for l in labels.keys() if l.endswith(hemi)]:
    data[labels[name].vertices, :] = values[name]
    
brain.add_data(data, min=0.1, max=1, mid=0.5, center=None,
               transparent=True, colormap='auto', 
               time=np.arange(T), hemi=hemi, 
               remove_existing=True)
```

**Comment by agramfort** [comment] 2018-10-19 11:52
I see this on my machine using the MNE conda env (macos)

<img width="790" alt="screen shot 2018-10-19 at 13 50 37" src="https://user-images.githubusercontent.com/161052/47216662-04997d80-d3a6-11e8-8fe2-92c604d10771.png">

I edited the comment above so it's more self contained.

**Comment by larsoner** [comment] 2018-10-19 14:01
Don't use unseeded random in a MWE it changes the result on each run. I've updated the example to seed it and set the view to approximately what @sbitzer originally had, and this is what I get on Linux. I don't see any labels coming through to the other side:

![screenshot from 2018-10-19 10-00-15](https://user-images.githubusercontent.com/2365790/47222854-c8eebb80-d385-11e8-803e-49fcf79fb38b.png)

@sbitzer can you try the updated MWE and see if you get the same thing? If it looks correct, hopefully you can isolate the problem based on the difference between the MWE and your original code.

**Comment by larsoner** [comment] 2018-10-19 14:03
... ahh just noticed you said it was machine related. Yes it's probably an OpenGL rendering problem then.

One thing you can try is using `brain.toggle_toolbars(True)` to get to the Mayavi properties of the surfaces. Perhaps changing the alpha / opacity of one or more of them to 0.99 instead of 1.0 will fix the problem by using alpha blending rather than z-order to do the rendering. You can also try tweaking other params to see if it helps but this is the one I'd try first.

**Comment by sbitzer** [comment] 2018-10-21 13:06
Thanks for the tip with the toolbars! For reference, this is the figure, when I generate it:
![transparency](https://user-images.githubusercontent.com/320128/47267048-a2c04b80-d53e-11e8-8c5f-59f9f74c484c.png)

Clicking through the Mayavi pipeline I found an option for "Backface culling" which works as a work-around. It is under fsaverage->VTK DATA (PolyData) -> Surface -> Property -> More options. Switching backface culling on removes the transparency issues and recovers the expected visualisation as shown in your screenshot. Manipulating the opacity values of the two shown surfaces did not have the desired effect.

**Comment by larsoner** [comment] 2018-10-22 14:21
Even though I'm pretty sure this is a graphics card bug, it shouldn't hurt anything (might actually help performance) to enable back-face culling. I'll make a PR

**Comment by larsoner** [comment] 2018-10-22 14:54
Actually it looks like it does not always fix the problem and has some effects people might not always expect.

I think this is a VTK rendering bug so I'll close this, but we at least have the workaround noted for people in case they want to use it. FYI this backface culling can be scripted, too, with things like:
```
surf.actor.property.backface_culling = True
```
... once you find the correct `surf` in the scene / from the `Brain` object somewhere.

**Closed by larsoner** 2018-10-22 14:54 UTC

**Comment by mylee5661** [comment] 2019-01-03 17:06
wow, that just solve my problem
thank you very much

**Comment by irebollo** [comment] 2019-04-29 12:54
I had the same problem while making surface and I came to an alternative solution (tried to fish the surf in the scene / from the Brain object somewhere but it was impossible. It would be helpful to explicit the structure of the brain object in further documentation


Apparently the backface_culling propery is set to defualt to true when ploting surfaces
from viz:py, lines 3159 to 3175
    def add_overlay(self, old):
        """Add an overlay to the overlay dict from a file or array"""
        array_id, mesh = self._add_scalar_data(old.mlab_data)

        if old.pos_lims is not None:
            with warnings.catch_warnings(record=True):
                pos_thresh = threshold_filter(mesh, low=old.pos_lims[0])
                pos = mlab.pipeline.surface(
                    pos_thresh, colormap="YlOrRd", figure=self._f,
                    vmin=old.pos_lims[1], vmax=old.pos_lims[2],
                    reset_zoom=False)
                pos.actor.property.backface_culling = True
                pos_bar = mlab.scalarbar(pos, nb_labels=5)
            pos_bar.reverse_lut = True
            pos_bar.scalar_bar_representation.position = (0.53, 0.01)
            pos_bar.scalar_bar_representation.position2 = (0.42, 0.09)
            pos_bar.label_text_property.color = self._fg_color

Setting line 3170 to 
                pos.actor.property.backface_culling = True
And relaunching my script solved the problem

great tool!now that is working properly I hope to get some nice surface plots
Thanks!

Perhaps

**Comment by irebollo** [comment] 2019-04-29 12:56
Alternative is to change                 pos.actor.property.backface_culling = True
on viz.py

it would also be helpful to explicit the brain object structure in further documentation
thanks for this amazing tool!

lines 31359
    def add_overlay(self, old):
        """Add an overlay to the overlay dict from a file or array"""
        array_id, mesh = self._add_scalar_data(old.mlab_data)

        if old.pos_lims is not None:
            with warnings.catch_warnings(record=True):
                pos_thresh = threshold_filter(mesh, low=old.pos_lims[0])
                pos = mlab.pipeline.surface(
                    pos_thresh, colormap="YlOrRd", figure=self._f,
                    vmin=old.pos_lims[1], vmax=old.pos_lims[2],
                    reset_zoom=False)
                pos.actor.property.backface_culling = True
                pos_bar = mlab.scalarbar(pos, nb_labels=5)
            pos_bar.reverse_lut = True
            pos_bar.scalar_bar_representation.position = (0.53, 0.01)
            pos_bar.scalar_bar_representation.position2 = (0.42, 0.09)
            pos_bar.label_text_property.color = self._fg_color

**Comment by mjallais** [comment] 2021-01-22 08:44
I encountered a similar issue when displaying the plots, which was probably due to a VTK rendering bug. To solve it, I created a new clean environment and ran the following:
```conda create -n pysurfer_env python=3.7
conda activate pysurfer_env
conda install vtk
pip install --no-cache pyvista
pip install pysurfer
conda install pyqt
```
Watch out to use the conda environment's pip command. 
Hope that helps !

**Comment by Davi1990** [comment] 2021-06-07 00:57
I had the same issue with using MNE to plot the source estimate 

![Screen Shot 2021-06-06 at 20 55 14](https://user-images.githubusercontent.com/37826571/120946247-d4937a00-c709-11eb-8941-dc9883dc2651.png)


`surf.actor.property.backface_culling = True` didn't solve the issue in my case

**Comment by agramfort** [comment] 2021-06-07 08:14
this code in MNE is not using pysurfer but just vtk (it's using pyvista).

>

**Comment by Davi1990** [comment] 2021-06-07 11:48
Hi @agramfort, I know but I was wondering whether you have a solution to that. I have this issue for different MNE version and independent laptop

**Comment by agramfort** [comment] 2021-06-07 13:37
did you have a look at
https://mne.tools/dev/install/advanced.html#troubleshooting-3d-plots ?

>

**Comment by Davi1990** [comment] 2021-06-07 14:07
Yes, I actually did before start commenting this issue but I didn't help

**Comment by agramfort** [comment] 2021-06-07 14:34
I don't know what else to suggest then. You'll have to maybe see what is
common between
the different machines you tested on to infer the cause of your problem

>

**Comment by larsoner** [comment] 2021-06-08 15:04
To me it looks like the depth buffer is treated properly on one system / graphics card and not on the other
